### ISSUE TITLE
Disable knex-stringcase for specific query

### ISSUE THREAD

**Issue by niklv** [Kequc/knex-stringcase#15]
Is it possible to disable knex-stringcase for specific query? 
`ignoreStringcase` is not an option for me, cause I need raw column names only for one specific query, and convert this column names to camelCase in another queries.

**Comment by Kequc** [comment]
Hi, `ignoreStringcase` only deals with individual objects. I didn't consider someone might want to disable stringcase for a query. I'm not certain how I would implement that because the methods this library uses are intended to be used across all interactions with the database.

I'm open to suggestions here or in the form of PR.

**Comment by Kequc** [comment]
After doing a bit of looking into it my suspicions are confirmed, there is no way to skip use of `postProcessResponse` or `wrapIdentifier`. This would be a task for knex.js to handle, as my library is only configuration.
