### ISSUE TITLE
Table identifiers vs column identifiers

### ISSUE THREAD

**Issue by bojanmilosavljevic** [Kequc/knex-stringcase#26]
Hi!

I have a very old specific database and was wondering whether it would be possible to discern between table names and column names namely I don't want my column names converted to upper case snake case, while I do want that for my columns. Would there be any way of achievingthis? 

Thanks for the help!

**Comment by Kequc** [comment]
That is a very reasonable request.

Knex unfortunately does not seem to differentiate (if you find out otherwise I'd be interested to know what you find!) as it calls all things "identifier names". This library only makes use of knex's in-built 'wrapIdentifier' and 'postProcessResponse' methods, so there doesn't apparently seem to be any way to tell the difference.

https://knexjs.org/guide/#wrapidentifier
https://knexjs.org/guide/#postprocessresponse

If you can differentiate programmatically between table names and column names you could write your own function which performs the conversion. For 'stringcase' and 'appStringcase' write functions something like:

```javascript
{
    stringcase (value) => isTable(value) ? value : snakecase(value),
    appStringcase (value) => isTable(value) ? value : camelcase(value)
}
```
